// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8GqaCvbIhlkVHfa2eQfQhxFUIFPhSiM8',
    appId: '1:155305234820:web:0194e71e79e290a0e98dd1',
    messagingSenderId: '155305234820',
    projectId: 'learnall-fc31d',
    authDomain: 'learnall-fc31d.firebaseapp.com',
    storageBucket: 'learnall-fc31d.appspot.com',
    measurementId: 'G-JT0X8NL58K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe3KlMyQihq_He1cE_UXdnBxzCJiQBxDk',
    appId: '1:155305234820:android:1cddc883e9fb89e2e98dd1',
    messagingSenderId: '155305234820',
    projectId: 'learnall-fc31d',
    storageBucket: 'learnall-fc31d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAx6jLQ6CVJEZDcfUqUK3dXgsyVGzleHM',
    appId: '1:155305234820:ios:430e219970aa3eb1e98dd1',
    messagingSenderId: '155305234820',
    projectId: 'learnall-fc31d',
    storageBucket: 'learnall-fc31d.appspot.com',
    iosBundleId: 'com.example.learnAll',
  );

}